# Generated by Django 5.0.6 on 2024-05-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=120, unique=True, verbose_name='Английское название')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название группы товаров')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Краткое описание')),
                ('seo_description', models.CharField(blank=True, max_length=1350, verbose_name='СЕО описание')),
                ('seo_keywords', models.CharField(blank=True, max_length=1350, verbose_name='СЕО ключевые слова')),
                ('seo_title', models.CharField(blank=True, max_length=250, verbose_name='SEO краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('priority', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
