# Generated by Django 5.0.6 on 2024-07-15 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_image_alter_article_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='seo_title',
        ),
        migrations.AddField(
            model_name='article',
            name='datetime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
