services:
  db:
    image: postgres:15
    container_name: db_app

    environment:
      - POSTGRES_DB=RWP
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=89908990aSa
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
#    env_file:
#      - .env
  app:
    image: rwp_site_prod-app
    environment:
      - POSTGRES_DB=RWP
      - POSTGRES_NAME=RWP
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=89908990aSa
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    container_name: django_app
    ports:
      - 9999:8000

    command: ["docker/app.sh"]
    depends_on:
      - db


